global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts/navi-slos.yaml

scrape_configs:
  - job_name: 'navi-backend'
    metrics_path: /metrics/metrics
    static_configs:
      - targets: ['host.docker.internal:8787']
