apiVersion: v1
kind: Service
metadata:
  name: navi-backend
  namespace: navi-prod
spec:
  type: ClusterIP
  selector:
    app: navi-backend
  ports:
    - name: http
      port: 80
      targetPort: 8787
